todoapp/accounts/urls.py
from django.urls import path
from .views import login_view, logout_view

# app name to be used for url templating
app_name = 'accounts'

urlpatterns = [
    path('login', login_view, name="login"),
    path('logout', logout_view, name="logout"),
]

todoapp/tasks/urls.py
from django.urls import path
from .views import task_create, task_list

# app name to be used for url templating
app_name = 'tasks'

urlpatterns = [
    path('', task_list, name="list"),
    path('create', task_create, name="create"),
]

todoapp/todoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('tasks/', include('tasks.urls')),
    path('', home_view),
]

todoapp/accounts/models.py
from django.db import models

# Create your models here.

todoapp/tasks/models.py
from django.db import models
from django.contrib.auth.models import User


class Priority(models.Model):
    """
    Model for Priority
    """
    label = models.CharField(max_length=10)

    def __str__(self):
        return self.label


class Task(models.Model):
    """
    Model for Task
    """
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    priority = models.ForeignKey(Priority, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_completed = models.BooleanField(default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)

    class Meta:
        ordering = ['timestamp', ]

    def __str__(self):
        return self.title

todoapp/tasks/forms.py
from django import forms
from . import models


class CreateTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ["title", "description", "priority", "is_completed"]

todoapp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


def login_view(request):
    """
    Login view to display login form and authenticate user.
    :param request: request object
    :return:
    For GET, login.html template
    For POST, authenticate and redirect the user to corresponding view
    """
    try:
        if request.method == "POST":
            # serialize form data from the request
            form = AuthenticationForm(data=request.POST)

            # check for valid form
            if form.is_valid():
                # get user from the form
                user = form.get_user()

                # login user
                login(request, user)

                # checking if user need to redirect to some other route
                if "next" in request.POST:
                    return redirect(request.POST.get("next"))
                return redirect('tasks:list')
        else:
            # create authentication form and send the instance to template for rendering
            form = AuthenticationForm()
            return render(request, 'accounts/login.html', {'form': form})
    except Exception as e:
        # Todo: change this to redirect at error page
        print(e)
        # return redirect('accounts:login')


def logout_view(request):
    """
    Logout view to close the user session.
    :param request: request object
    :return:
    For POST, logout and redirect the user to login page.
    """
    try:
        if request.method == "POST":
            logout(request)
            return redirect('accounts:login')
    except Exception as e:
        # Todo: change this to redirect at error page
        print(e)
        return redirect('accounts:login')

todoapp/tasks/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from . import forms
from .models import Task


@login_required(login_url="accounts/login")
def task_list(request):
    """
    List all the tasks created by user.
    :param request: request object
    :return: template with rendered list of all the tasks
    """
    try:
        # fetch all the tasks
        tasks = Task.objects.all()
        return render(request, 'tasks/list_tasks.html', {'tasks': tasks})
    except Exception as e:
        # Todo: change this to redirect at error page
        return redirect('accounts:login')


@login_required(login_url="accounts/login")
def task_create(request):
    """
    Create the task for the user.
    :param request: request object
    :return:
    GET: template to render create task form
    POST: Save the user task and redirect to tasks page
    """
    try:
        if request.method == "POST":
            form = forms.CreateTask(data=request.POST)
            if form.is_valid():
                instance = form.save(commit=False)
                # adding author to the task
                instance.author = request.user
                form.save()
                return redirect('tasks:list')
        else:
            # create task form
            task_form = forms.CreateTask()
            return render(request, 'tasks/create_task.html', {'form': task_form})
    except Exception as e:
        # Todo: change this to redirect at error page
        return redirect('accounts:login')

todoapp/todoapp/views.py
from django.shortcuts import render, redirect


def home_view(request):
    """
    Home view to display welcome message(landing page).
    :param request: request object
    :return:
    home.html template
    """
    try:
        return render(request, 'home.html')
    except Exception as e:
        # Todo: change this to redirect at error page
        print(e)
        return redirect('accounts:login')

todoapp/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<form class="login-form" action="{% url 'accounts:login' %}" method="post">
    {{form}}
    {% csrf_token %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <input type="submit" value="Login">
</form>
{% endblock %}

todoapp/tasks/templates/tasks/create_task.html
{% extends 'base_layout.html' %}
{% block content %}
    <form class="create-task-form" action="{% url 'tasks:create' %}" method="post">
        {{form}}
        {% csrf_token %}
        <input type="submit" value="Save task">
    </form>
{% endblock %}

todoapp/tasks/templates/tasks/list_tasks.html
{% extends 'base_layout.html' %}
{% block content %}
    <a href="{% url 'tasks:create' %}">Create a new task</a>
    <p>Filter task by:</p>

    <h3>List of tasks:</h3>
    {% for task in tasks %}
        <p>Task name: {{task.title}}</p>
        <p>Description: {{task.description}}</p>
        <p>Priority: {{task.priority}}</p>
        <hr/>
    {% endfor%}
{% endblock %}

todoapp/templates/base_layout.html
<!DOCTYPE html>
{% load static from static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ToDo App</title>
    <link rel="stylesheet" href="{% static 'styles.css'%}" />
</head>
<body>
    <header>
        <nav>
            {% if user.is_authenticated %}
                <form class="logout-form" action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Logout">
                </form>
            {% else %}
                <a class="user-login" href="{% url 'accounts:login' %}">Login</a>
            {% endif%}
        </nav>
    </header>
    {% block content %}
    {% endblock %}
</body>
</html>

todoapp/templates/home.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="main-message">
    <h1>Welcome to To-Do Application.</h1>
    {% if not user.is_authenticated %}
        <h2>Please login to continue</h2>
    {% endif %}
</div>
{% endblock %}